//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legacy.PerformSTTFromFile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Legacy.PerformSTTFromFile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified audio file does not exist..
        /// </summary>
        internal static string AudioFileNotFound {
            get {
                return ResourceManager.GetString("AudioFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file path is required..
        /// </summary>
        internal static string AudioFilePathRequired {
            get {
                return ResourceManager.GetString("AudioFilePathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCELED: Reason = {0}\nErrorCode = {1}\nErrorDetails = {2}\nDid you set the speech resource key and region values correctly?.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale is required..
        /// </summary>
        internal static string LocaleRequired {
            get {
                return ResourceManager.GetString("LocaleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOMATCH: Speech could not be recognized..
        /// </summary>
        internal static string NoMatch {
            get {
                return ResourceManager.GetString("NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOGNIZED: Text = {0}.
        /// </summary>
        internal static string RecognizedText {
            get {
                return ResourceManager.GetString("RecognizedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service region is required..
        /// </summary>
        internal static string ServiceRegionRequired {
            get {
                return ResourceManager.GetString("ServiceRegionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech recognition failed: {0}.
        /// </summary>
        internal static string SpeechRecognitionFailed {
            get {
                return ResourceManager.GetString("SpeechRecognitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription key is required..
        /// </summary>
        internal static string SubscriptionKeyRequired {
            get {
                return ResourceManager.GetString("SubscriptionKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN ERROR: Unable to process speech..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
